server:
  port: 18080

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
  data:
    redis:
      host: localhost
      port: 6379
      sentinel:
        username: default
        password: systempass
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
